include: package:flutter_lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    close_sinks: ignore

linter:
  rules:
    non_constant_identifier_names: false
    sort_child_properties_last: false